#!/bin/bash
set -eu

# Resource Directories
export ROOT_PATH="$(pwd)"
export REPO_ROOT="${ROOT_PATH}/git"
export BUILD_ROOT="${ROOT_PATH}/build"
export CI_ROOT="${ROOT_PATH}/git-ci"
export VERSION_FROM="${ROOT_PATH}/version/number"

header() {
	echo
	echo "================================================================================"
	echo "$1"
	echo "--------------------------------------------------------------------------------"
	echo
}

bail() {
	echo >&2 "$*  Did you misconfigure Concourse?"
	exit 2
}
test -n "${APP_NAME:-}"       || bail "APP_NAME must be set to the name of this package."
test -f "${VERSION_FROM}"     || bail "Version file (${VERSION_FROM}) not found."
VERSION=$(cat "${VERSION_FROM}")
test -n "${VERSION}"          || bail "Version file (${VERSION_FROM}) was empty."

cd "$REPO_ROOT"
go version;

header "Building $APP_NAME v$VERSION..."

make clean release VERSION=$VERSION APP_NAME=$APP_NAME
cd builds
tar -zcvf $BUILD_ROOT/${APP_NAME}-${VERSION}.tar.gz $APP_NAME-*

echo
echo "================================================================================"
echo "SUCCESS!"
exit 0
