---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: registry.ops.scalecf.net/genesis-community/concourse-go
    tag: latest

inputs:
- name: git
- name: git-ci
- name: version
- name: build

outputs:
- name: work

params:
  GIT_CI:   git-ci
  CF_API:   ((cloud-foundry.url))
  CF_USER:  ((cloud-foundry.username))
  CF_PASS:  ((cloud-foundry.password))
  CF_ORG:   ci
  CF_SPACE: test

run:
  path: git-ci/ci/scripts/test
