// render-cron-help reads cron-expression-reference.md and renders it
// in every glamour default style, then writes a single Go source file
// (cron_expression_styles.go) containing all rendered output as a
// map[string]string.
//
// Usage: go run ./cmd/render-cron-help
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/charmbracelet/glamour"
	"github.com/charmbracelet/glamour/styles"
)

func main() {
	src, err := os.ReadFile("cron-expression-reference.md")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading markdown: %v\n", err)
		os.Exit(1)
	}

	// tableStyle := []byte(`{"table":{"center_separator":"┼","column_separator":"│","row_separator":"─"}}`)

	names := make([]string, 0, len(styles.DefaultStyles))
	for name := range styles.DefaultStyles {
		names = append(names, name)
	}
	sort.Strings(names)

	rendered := make(map[string]string, len(names))
	for _, name := range names {
		out, err := render(string(src), name)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error rendering markdown with style %q: %v\n", name, err)
			os.Exit(1)
		}

		rendered[name] = out
	}

	// Ensure a "notty" style always exists. If glamour didn't provide one,
	// generate it using the ASCII style (plain text, no ANSI escapes).
	if _, ok := rendered["notty"]; !ok {
		styleName := "ascii"
		if _, ok := rendered[styleName]; !ok {
			// Neither notty nor ascii from glamour — render with NoTTY options.
			styleName = "notty"
		}
		out, err := render(string(src), styleName)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error rendering fallback notty style: %v\n", err)
			os.Exit(1)
		}
		rendered["notty"] = out
		names = append(names, "notty")
		sort.Strings(names)
	}

	f, err := os.Create("cron_expression_styles.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating Go source file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by cmd/render-cron-help; DO NOT EDIT.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "package main")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "var cronExpressionStyles = map[string]string{")
	for _, name := range names {
		fmt.Fprintf(f, "\t%q: %q,\n", name, rendered[name])
	}
	fmt.Fprintln(f, "}")
}

func render(src, style string) (string, error) {
	renderer, err := glamour.NewTermRenderer(
		glamour.WithStylePath(style),
		// glamour.WithStylesFromJSONBytes(tableStyle),
		glamour.WithWordWrap(78),
		glamour.WithTableWrap(true),
	)
	if err != nil {
		return "", err
	}
	out, err := renderer.Render(protectHyphens(src))
	return strings.ReplaceAll(out, nbHyphen, "-"), err
}

// nbHyphen stands in for "-" while rendering. glamour's paragraph wrap
// (muesli/reflow) breaks at hyphens but does not count them toward the
// line length, so lines run long and the document margin re-wraps them,
// leaving one-word orphan lines. Drop this once a fix ships:
//
//	https://github.com/muesli/reflow/issues/66
//	https://github.com/muesli/reflow/pull/79
//	https://github.com/charmbracelet/glamour/issues/407
//	https://github.com/charmbracelet/glamour/issues/451
const nbHyphen = "‑"

// protectHyphens swaps hyphens inside words for nbHyphen, leaving
// markdown syntax such as table rules and list markers alone.
func protectHyphens(s string) string {
	r := []rune(s)
	for i := 1; i < len(r)-1; i++ {
		if r[i] == '-' && !isMarkup(r[i-1]) && !isMarkup(r[i+1]) {
			r[i] = []rune(nbHyphen)[0]
		}
	}
	return string(r)
}

func isMarkup(c rune) bool {
	return c == '-' || c == '|' || c == ':' || unicode.IsSpace(c)
}
