// render-cron-help reads cron-expression-reference.md and renders it
// in every glamour default style, then writes a single Go source file
// (cron_expression_styles.go) containing all rendered output as a
// map[string]string.
//
// Usage: go run ./cmd/render-cron-help
package main

import (
	"fmt"
	"os"
	"sort"

	"github.com/charmbracelet/glamour"
	"github.com/charmbracelet/glamour/styles"
)

func main() {
	src, err := os.ReadFile("cron-expression-reference.md")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading markdown: %v\n", err)
		os.Exit(1)
	}

	// tableStyle := []byte(`{"table":{"center_separator":"┼","column_separator":"│","row_separator":"─"}}`)

	names := make([]string, 0, len(styles.DefaultStyles))
	for name := range styles.DefaultStyles {
		names = append(names, name)
	}
	sort.Strings(names)

	rendered := make(map[string]string, len(names))
	for _, name := range names {
		renderer, err := glamour.NewTermRenderer(
			glamour.WithStylePath(name),
			// glamour.WithStylesFromJSONBytes(tableStyle),
			glamour.WithWordWrap(78),
			glamour.WithTableWrap(true),
		)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error creating renderer for style %q: %v\n", name, err)
			os.Exit(1)
		}

		out, err := renderer.Render(string(src))
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error rendering markdown with style %q: %v\n", name, err)
			os.Exit(1)
		}

		rendered[name] = out
	}

	// Ensure a "notty" style always exists. If glamour didn't provide one,
	// generate it using the ASCII style (plain text, no ANSI escapes).
	if _, ok := rendered["notty"]; !ok {
		styleName := "ascii"
		if _, ok := rendered[styleName]; !ok {
			// Neither notty nor ascii from glamour — render with NoTTY options.
			styleName = "notty"
		}
		renderer, err := glamour.NewTermRenderer(
			glamour.WithStylePath(styleName),
			glamour.WithWordWrap(78),
			glamour.WithTableWrap(true),
		)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error creating fallback notty renderer: %v\n", err)
			os.Exit(1)
		}
		out, err := renderer.Render(string(src))
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error rendering fallback notty style: %v\n", err)
			os.Exit(1)
		}
		rendered["notty"] = out
		names = append(names, "notty")
		sort.Strings(names)
	}

	f, err := os.Create("cron_expression_styles.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating Go source file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by cmd/render-cron-help; DO NOT EDIT.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "package main")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "var cronExpressionStyles = map[string]string{")
	for _, name := range names {
		fmt.Fprintf(f, "\t%q: %q,\n", name, rendered[name])
	}
	fmt.Fprintln(f, "}")
}
